language: c

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      name: "Linux static library"
      dist: xenial
      env:
        - CLOGGER_SHARED=OFF
    - os: linux
      name: "Linux shared library"
      dist: xenial
      env:
        - CLOGGER_SHARED=ON
    - os: osx
      name: "OSX static library"
      env:
        - CLOGGER_SHARED=OFF
    - os: osx
      name: "OSX shared library"
      env:
        - CLOGGER_SHARED=ON

before_script:
  - mkdir build
  - cd build
  - cmake -DCLOGGER_SHARED=${CLOGGER_SHARED} ..

script:
  - cmake --build .