branches:
  only:
    - master

language: c
os:
  - linux
  - osx
  - windows

dist: xenial

compiler:
  - clang
  - gcc

env:
  - CLOGGER_SHARED=OFF
  - CLOGGER_SHARED=ON

addons:
  apt:
    packages:
      - cmake

before_script:
  - mkdir build
  - cd build
  - cmake -DCLOGGER_SHARED=${CLOGGER_SHARED} ..

script:
  - cmake -- build .
